// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include <odb/database.hxx>
#include <odb/schema-catalog-impl.hxx>

#include <odb/details/unused.hxx>

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS `Man_pets`");
          db.execute ("DROP TABLE IF EXISTS `Man`");
          db.execute ("DROP TABLE IF EXISTS `Animal`");
          db.execute ("DROP TABLE IF EXISTS `Base`");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE `Base` (\n"
                      "  `id` VARCHAR(36) NOT NULL PRIMARY KEY,\n"
                      "  `typeid` VARCHAR(128) NOT NULL)\n"
                      " ENGINE=InnoDB");
          db.execute ("CREATE TABLE `Animal` (\n"
                      "  `id` VARCHAR(36) NOT NULL PRIMARY KEY,\n"
                      "  `nickname` TEXT NOT NULL,\n"
                      "  CONSTRAINT `Animal_id_fk`\n"
                      "    FOREIGN KEY (`id`)\n"
                      "    REFERENCES `Base` (`id`)\n"
                      "    ON DELETE CASCADE)\n"
                      " ENGINE=InnoDB");
          db.execute ("CREATE TABLE `Man` (\n"
                      "  `id` VARCHAR(36) NOT NULL PRIMARY KEY,\n"
                      "  `name` TEXT NOT NULL,\n"
                      "  CONSTRAINT `Man_id_fk`\n"
                      "    FOREIGN KEY (`id`)\n"
                      "    REFERENCES `Base` (`id`)\n"
                      "    ON DELETE CASCADE)\n"
                      " ENGINE=InnoDB");
          db.execute ("CREATE TABLE `Man_pets` (\n"
                      "  `object_id` VARCHAR(36) NOT NULL,\n"
                      "  `index` BIGINT UNSIGNED NOT NULL,\n"
                      "  `value` VARCHAR(36) NULL,\n"
                      "  CONSTRAINT `Man_pets_object_id_fk`\n"
                      "    FOREIGN KEY (`object_id`)\n"
                      "    REFERENCES `Man` (`id`)\n"
                      "    ON DELETE CASCADE)\n"
                      " ENGINE=InnoDB");
          db.execute ("CREATE INDEX `object_id_i`\n"
                      "  ON `Man_pets` (`object_id`)");
          db.execute ("CREATE INDEX `index_i`\n"
                      "  ON `Man_pets` (`index`)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_mysql,
    "",
    &create_schema);
}

#include <odb/post.hxx>
